import { Router } from "express";
import { authMiddleware } from "../lib/auth-middleware.js";

const router = Router();
router.use(authMiddleware);

const TOPICS = [
  { id: "1", title: "What is Algorithmic Trading?", category: "Trading Basics", summary: "Algorithmic trading uses computer programs to execute trades based on pre-defined rules and conditions.", url: "https://www.investopedia.com/terms/a/algorithmictrading.asp", difficulty: "beginner", source: "Investopedia" },
  { id: "2", title: "Understanding Risk Management in Crypto", category: "Risk Management", summary: "Effective risk management protects capital by setting exposure limits, stop-losses, and position sizing rules.", url: "https://www.investopedia.com/terms/r/riskmanagement.asp", difficulty: "intermediate", source: "Investopedia" },
  { id: "3", title: "Market Making vs. Directional Trading", category: "Strategy", summary: "Market making profits from bid-ask spreads, while directional trading bets on price movements in a specific direction.", url: "https://www.investopedia.com/terms/m/marketmaker.asp", difficulty: "intermediate", source: "Investopedia" },
  { id: "4", title: "Understanding Order Types", category: "Trading Basics", summary: "Market, limit, stop, and stop-limit orders each have distinct execution characteristics that affect fill price and certainty.", url: "https://www.investopedia.com/trading/getting-know-order-types/", difficulty: "beginner", source: "Investopedia" },
  { id: "5", title: "What is a Kill Switch?", category: "Risk Management", summary: "A trading kill switch is a safety mechanism that immediately halts all trading activity when risk thresholds are breached.", url: "https://www.investopedia.com", difficulty: "intermediate", source: "Investopedia" },
  { id: "6", title: "Crypto Exchange Architecture", category: "Technology", summary: "Modern crypto exchanges use matching engines, order books, and settlement layers to process millions of trades per second.", url: "https://www.investopedia.com", difficulty: "advanced", source: "Investopedia" },
  { id: "7", title: "Dollar-Cost Averaging in Crypto", category: "Strategy", summary: "DCA involves investing fixed amounts at regular intervals regardless of price, reducing the impact of volatility.", url: "https://www.investopedia.com/terms/d/dollarcostaveraging.asp", difficulty: "beginner", source: "Investopedia" },
  { id: "8", title: "Technical Analysis Fundamentals", category: "Analysis", summary: "Technical analysis uses price charts, volume data, and indicators to identify trading opportunities and trends.", url: "https://www.investopedia.com/terms/t/technicalanalysis.asp", difficulty: "intermediate", source: "Investopedia" },
];

const DEFINITIONS = [
  { term: "Guardian", definition: "The guardian is the risk supervision layer that monitors all trading activity and enforces risk policies above all other system logic.", example: "The guardian detected exposure exceeding 85% of limit and halted new order placement.", relatedTerms: ["Kill Switch", "Risk Management", "Exposure"], url: "https://www.investopedia.com", source: "Investopedia" },
  { term: "Kill Switch", definition: "An emergency mechanism that immediately halts all trading activity across all connected exchanges when triggered manually or by risk breach.", example: "The kill switch was activated when daily losses exceeded the configured maximum.", relatedTerms: ["Guardian", "Risk Management"], url: "https://www.investopedia.com", source: "Investopedia" },
  { term: "Exposure", definition: "The total market value of open positions expressed as a dollar amount or percentage of total capital at risk.", example: "Current exposure is $12,400 (24.8% of $50,000 capital).", relatedTerms: ["Position Sizing", "Risk Management"], url: "https://www.investopedia.com", source: "Investopedia" },
  { term: "PnL", definition: "Profit and Loss — the realized and unrealized gains or losses from trading activity over a defined period.", example: "Daily PnL is +$340.50, representing a +0.75% return on deployed capital.", relatedTerms: ["Realized PnL", "Unrealized PnL"], url: "https://www.investopedia.com", source: "Investopedia" },
  { term: "Routing Decision", definition: "The engine's selection of which exchange to route a trade to based on liquidity, latency, fees, and risk parameters.", example: "Signal for BTC-USDT was routed to BTCC due to better liquidity depth.", relatedTerms: ["Exchange Adapter", "Smart Order Routing"], url: "https://www.investopedia.com", source: "Investopedia" },
  { term: "Signal", definition: "A data-driven trigger generated by the trading engine indicating a potential buy or sell opportunity with confidence and direction.", example: "A long signal for ETH-USDT with 78% confidence and 4-hour horizon was generated.", relatedTerms: ["Prediction", "Strategy"], url: "https://www.investopedia.com", source: "Investopedia" },
];

router.get("/topics", (_req, res) => {
  res.json(TOPICS);
});

router.get("/definitions", (req, res) => {
  const { term } = req.query;
  if (term) {
    const filtered = DEFINITIONS.filter(d => d.term.toLowerCase().includes(String(term).toLowerCase()));
    res.json(filtered);
  } else {
    res.json(DEFINITIONS);
  }
});

export { router as educationRouter };
